### ISSUE TITLE
Illegal publication

### ISSUE THREAD

**Issue by quartexNOR** [teo-tsirpanis/hexlicense-mirror#1]
Expressing an intent of something, is not the same as actually doing it.
The code was never published to public domain.

Please remove this, or i will contact Github directly.

**Comment by teo-tsirpanis** [comment]
Done. Sorry about that.

**Comment by teo-tsirpanis** [comment]
Upon further investigations after deleting the repository, it turns out @quartexNOR had actually said quite unequivocally in [that blog post](https://jonlennartaasenden.wordpress.com/2018/09/06/hexlicense-patreon-and-all-that/) ([archive 1](https://web.archive.org/web/20191103192600/https://jonlennartaasenden.wordpress.com/2018/09/06/hexlicense-patreon-and-all-that/), [archive 2](https://archive.is/zIbwx)) that:

> ### For immediate release
> Effective immediately HexLicense is open-source, released under the GNU Lesser General Public License v3. You can [read the details of that license by clicking here](https://web.archive.org/web/20191103192600/https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3)).

GitHub has restored the repository after my request. Further communication with @quartexNOR is happening offline.
